% Alex Nulman, Dvir Segal and Hadas Shahar [30-Apr-18]
% The purpose of this script is to triangulate the left and right skeletons
% generated by OpenPose (using python script)

% Loads predefined stereo calibration data
m = load('stereoParams_6.25mmSquare.mat');
% lr.mat is the left and right skeletons generated by python
left_right_points = load('lr.mat');
% Get world points (x,y,z) using triangulate 
worldPoints = triangulate(left_right_points.l,left_right_points.r,m.stereoParams);

% Split points to start and end points
q1 = worldPoints(1:2:end,:);
q2 = worldPoints(2:2:end,:);

% Concat each start and end point to [[start, end] , [start, end], ...,
% [start, end]] list then  plot 3D points on viewer with 
% 3D line between each point
for elm = transpose(cat(2, q1,q2))
    plot3([elm(1);elm(4)], [elm(2);elm(5)], [elm(3);elm(6)])
    hold on
end

ax = gca;
props = {'CameraViewAngle','DataAspectRatio','PlotBoxAspectRatio'};
set(ax,props,get(ax,props));